<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="sqlDataSourceDemo.Default" MaintainScrollPositionOnPostback="true" %>

<%@ Register Src="~/Header/Header.ascx" TagPrefix="uc1" TagName="Header" %>
<uc1:Header runat="server" ID="Header" />


<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>

            <asp:Button ID="restaurantButton" runat="server" Text="Get all restaurants information" OnClick="restaurantButton_Click" />
            <br />
            <br />
            <asp:GridView ID="RestaurantGrid" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" runat="server" AutoGenerateColumns="False" Visible="false" DataSourceID="restaurantDataSource" DataKeyNames="Rest_id">
                <Columns>
                    <asp:BoundField DataField="Rest_id" HeaderText="Restaurant id" SortExpression="Rest_id" ReadOnly="True" />
                    <asp:BoundField DataField="Rest_name" HeaderText="Restaurant name" SortExpression="Rest_name" />
                    <asp:BoundField DataField="Rest_street" HeaderText="Restaurant street" SortExpression="Rest_street" />
                    <asp:BoundField DataField="Rest_city" HeaderText="Restaurant city" SortExpression="Rest_city" />
                    <asp:BoundField DataField="Rest_state" HeaderText="Restaurant state" SortExpression="Rest_state" />
                    <asp:BoundField DataField="Rest_zip" HeaderText="Restaurant zip" SortExpression="Rest_zip" />
                    <asp:BoundField DataField="Rest_capacity" HeaderText="Restaurant capacity" SortExpression="Rest_capacity" />
                    <asp:BoundField DataField="Rest_pnum" HeaderText="Restaurant phone number" SortExpression="Rest_pnum" />
                </Columns>
            </asp:GridView>
            <br />
            <asp:DetailsView ID="RestaurantDetailView" runat="server" DataSourceID="restaurantDataSource" Visible="false">
                <Fields>
                    <asp:CommandField ShowInsertButton="true" />
                </Fields>
            </asp:DetailsView>
            <asp:SqlDataSource ID="restaurantDataSource" runat="server" ConnectionString="<%$ ConnectionStrings:WebAppConnString %>"
                ProviderName="<%$ ConnectionStrings:WebAppConnString.ProviderName %>"
                InsertCommand="INSERT INTO RESTAURANT VALUES(@Rest_id,@Rest_name,@Rest_street,@Rest_city,@Rest_state,@Rest_zip,@Rest_capacity,@Rest_pnum)"
                SelectCommand="SELECT * FROM RESTAURANT"
                DeleteCommand="DELETE FROM RESTAURANT WHERE (Rest_id = @Rest_id)"
                UpdateCommand="UPDATE restaurant SET Rest_name =@Rest_name, Rest_street =@Rest_street, 
            Rest_city =@Rest_city, Rest_state =@Rest_state, Rest_zip =@Rest_zip, Rest_capacity =@Rest_capacity, Rest_pnum =@Rest_pnum WHERE (Rest_id = @Rest_id)"></asp:SqlDataSource>

            <br />
            <br />

            <asp:Button ID="customerButton" runat="server" Text="Get all customers information" OnClick="customerButton_Click" />


            <br />
            <br />
            <asp:GridView ID="customerGrid" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" runat="server" AutoGenerateColumns="False" Visible="false" DataSourceID="customerDataSource" DataKeyNames="Cus_id">
                <Columns>
                    <asp:BoundField DataField="Cus_id" HeaderText="Customer id" SortExpression="Cus_id" ReadOnly="True" />
                    <asp:BoundField DataField="Cus_pno" HeaderText="Customer phone number" SortExpression="Cus_pno" />
                    <asp:BoundField DataField="Cus_fanme" HeaderText="Customer first name" SortExpression="Cus_fanme" />
                    <asp:BoundField DataField="Cus_mname" HeaderText="Customer middle name" SortExpression="Cus_mname" />
                    <asp:BoundField DataField="Cus_lname" HeaderText="Customer last name" SortExpression="Cus_lname" />
                    <asp:BoundField DataField="Cus_street" HeaderText="Customer street" SortExpression="Cus_street" />
                    <asp:BoundField DataField="Cus_city" HeaderText="Customer city" SortExpression="Cus_city" />
                    <asp:BoundField DataField="Cus_state" HeaderText="Customer state" SortExpression="Cus_state" />
                    <asp:BoundField DataField="Cus_zip" HeaderText="Customer zip" SortExpression="Cus_zip" />
                </Columns>
            </asp:GridView>
            <br />
            <asp:DetailsView ID="customerDetailsView" runat="server" DataSourceID="customerDataSource" Visible="false">
                <Fields>
                    <asp:CommandField ShowInsertButton="true" />
                </Fields>
            </asp:DetailsView>
            <asp:SqlDataSource ID="customerDataSource" runat="server" ConnectionString="<%$ ConnectionStrings:WebAppConnString %>"
                ProviderName="<%$ ConnectionStrings:WebAppConnString.ProviderName %>"
                SelectCommand="SELECT * FROM CUSTOMER"
                InsertCommand="INSERT INTO CUSTOMER VALUES(@Cus_id,@Cus_pno,@Cus_fanme,@Cus_mname,@Cus_lname,@Cus_street,@Cus_city,@Cus_state,@Cus_zip)"
                DeleteCommand="DELETE FROM CUSTOMER WHERE (Cus_id = @Cus_id)"
                UpdateCommand="UPDATE CUSTOMER SET Cus_pno =@Cus_pno, Cus_fanme =@Cus_fanme, 
            Cus_mname =@Cus_mname, Cus_lname =@Cus_lname, Cus_street =@Cus_street, Cus_city =@Cus_city, Cus_state =@Cus_state, Cus_zip =@Cus_zip WHERE (Cus_id = @Cus_id)"></asp:SqlDataSource>

            <br />
            <br />
            <asp:Label ID="TableId" Text="Get table information for the selected restaurant" runat="server"></asp:Label>



            <asp:DropDownList ID="tableDropdown" DataSourceID="restaurantNameDataSource" runat="server" AutoPostBack="True"
                AppendDataBoundItems="true" DataTextField="Rest_name" DataValueField="Rest_id">
            </asp:DropDownList>
            <asp:SqlDataSource ID="restaurantNameDataSource" runat="server" ConnectionString="<%$ ConnectionStrings:WebAppConnString %>"
                ProviderName="<%$ ConnectionStrings:WebAppConnString.ProviderName %>"
                SelectCommand="SELECT Rest_name,Rest_id FROM RESTAURANT"></asp:SqlDataSource>
            <asp:Button ID="tableButton" runat="server" Text="Submit" OnClick="tableButton_Click" />

            <asp:GridView ID="tableGrid" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" runat="server" AutoGenerateColumns="False" Visible="false" DataSourceID="tableDataSource" DataKeyNames="Table_id,Table_restid">
                <Columns>
                    <asp:BoundField DataField="Table_id" HeaderText="Table id" SortExpression="Table_id" ReadOnly="True" />
                    <asp:BoundField DataField="Table_restid" HeaderText="Restaurant id" SortExpression="Table_restid" ReadOnly="True" />
                    <asp:BoundField DataField="Table_size" HeaderText="Table size" SortExpression="Table_size" />
                    <asp:BoundField DataField="Table_position" HeaderText="Table position" SortExpression="Table_position" />
                </Columns>
            </asp:GridView>
            <br />
            <asp:DetailsView ID="tableDetailsView" runat="server" DataSourceID="DetailTableDataSource" Visible="false">
                <Fields>
                    <asp:CommandField ShowInsertButton="true" />
                </Fields>
            </asp:DetailsView>
            <asp:SqlDataSource ID="DetailTableDataSource" runat="server" ConnectionString="<%$ ConnectionStrings:WebAppConnString %>"
                ProviderName="<%$ ConnectionStrings:WebAppConnString.ProviderName %>"
                SelectCommand="SELECT * from RES_TABLE"
                InsertCommand="INSERT INTO RES_TABLE VALUES(@Table_id,@Table_restid,@Table_size,@Table_position)"></asp:SqlDataSource>
            <asp:SqlDataSource ID="tableDataSource" runat="server" ConnectionString="<%$ ConnectionStrings:WebAppConnString %>"
                ProviderName="<%$ ConnectionStrings:WebAppConnString.ProviderName %>"
                InsertCommand="INSERT INTO RES_TABLE VALUES(@Table_id,@Table_restid,@Table_size,@Table_position)"
                DeleteCommand="DELETE FROM RES_TABLE WHERE (Table_id = @Table_id) AND (Table_restid =@Table_restid)"
                UpdateCommand="UPDATE RES_TABLE SET Table_size =@Table_size, Table_position =@Table_position WHERE Table_restid =@Table_restid AND Table_id = @Table_id"
                SelectCommand="SELECT * from RES_TABLE where Table_restid=@RestaurantId1">
                <SelectParameters>
                    <asp:ControlParameter ControlID="tableDropdown" Name="RestaurantId1" PropertyName="SelectedValue" />
                </SelectParameters>
            </asp:SqlDataSource>


            <br />
            <br />

            <asp:Label ID="DishLabel" Text="Get Dish information for the selected restaurant" runat="server"></asp:Label>
            <asp:DropDownList ID="restaurantNameForDishDropDown" DataSourceID="restaurantNameDataSource" runat="server" AutoPostBack="True"
                AppendDataBoundItems="true" DataTextField="Rest_name" DataValueField="Rest_id">
            </asp:DropDownList>
            <asp:Button ID="DishButton" runat="server" Text="Submit" OnClick="DishButton_Click" />
            <asp:GridView ID="DishGrid" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" runat="server" AutoGenerateColumns="False" Visible="false"
                DataSourceID="DishDataSource" DataKeyNames="Dish_id,Dish_restid">
                <Columns>
                    <asp:BoundField DataField="Dish_id" HeaderText="Dish id" SortExpression="Dish_id" ReadOnly="True" />
                    <asp:BoundField DataField="Dish_restid" HeaderText="Restaurant id" SortExpression="Dish_restid" ReadOnly="True" />
                    <asp:BoundField DataField="Dish_name" HeaderText="Dish name" SortExpression="Dish_name" />
                    <asp:BoundField DataField="Dish_price" HeaderText="Dish price" SortExpression="Dish_price" />
                </Columns>
            </asp:GridView>
            <br />
            <asp:DetailsView ID="DishDetailsView" runat="server" DataSourceID="DetailDishDataSource" Visible="false">
                <Fields>
                    <asp:CommandField ShowInsertButton="true" />
                </Fields>
            </asp:DetailsView>
            <asp:SqlDataSource ID="DetailDishDataSource" runat="server" ConnectionString="<%$ ConnectionStrings:WebAppConnString %>"
                ProviderName="<%$ ConnectionStrings:WebAppConnString.ProviderName %>"
                SelectCommand="SELECT * from DISH"
                InsertCommand="INSERT INTO DISH VALUES(@Dish_id,@Dish_restid,@Dish_name,@Dish_price)"></asp:SqlDataSource>
            <asp:SqlDataSource ID="DishDataSource" runat="server" ConnectionString="<%$ ConnectionStrings:WebAppConnString %>"
                ProviderName="<%$ ConnectionStrings:WebAppConnString.ProviderName %>"
                DeleteCommand="DELETE FROM DISH WHERE (Dish_id = @Dish_id) AND (Dish_restid =@Dish_restid)"
                UpdateCommand="UPDATE DISH SET Dish_name =@Dish_name, Dish_price =@Dish_price WHERE (Dish_id = @Dish_id) AND (Dish_restid =@Dish_restid)"
                SelectCommand="SELECT * from DISH where Dish_restid=@RestaurantId2">
                <SelectParameters>
                    <asp:ControlParameter ControlID="restaurantNameForDishDropDown" Name="RestaurantId2" PropertyName="SelectedValue" />
                </SelectParameters>
            </asp:SqlDataSource>

            <br />
            <br />

            <asp:Label ID="reservationLabel1" Text="Get Reservation information for the customer" runat="server"></asp:Label>
            <asp:DropDownList ID="customerNameDropDown" DataSourceID="customerNameDataSource" runat="server" AutoPostBack="True"
                AppendDataBoundItems="true" DataTextField="Cus_Name" DataValueField="Cus_id">
            </asp:DropDownList>
            <asp:Label ID="reservationLabel2" Text=" in restaurant " runat="server"></asp:Label>
            <asp:DropDownList ID="restaurantIDDropDown" DataSourceID="restaurantNameDataSource" runat="server" AutoPostBack="True"
                AppendDataBoundItems="true" DataTextField="Rest_name" DataValueField="Rest_id">
            </asp:DropDownList>
            <asp:SqlDataSource ID="customerNameDataSource" runat="server" ConnectionString="<%$ ConnectionStrings:WebAppConnString %>"
                ProviderName="<%$ ConnectionStrings:WebAppConnString.ProviderName %>"
                SelectCommand="SELECT CONCAT(Cus_fanme ,' ',Cus_mname ,' ',Cus_lname) as Cus_Name,Cus_id FROM CUSTOMER"></asp:SqlDataSource>

            <asp:Button ID="reservationButton" runat="server" Text="Submit" OnClick="reservationButton_Click" />

            <asp:GridView ID="reservationGrid" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" runat="server" AutoGenerateColumns="False" Visible="false" DataSourceID="reservationDataSource" DataKeyNames="Resv_id,Resv_restid">
                <Columns>
                    <asp:BoundField DataField="Resv_id" HeaderText="Reservation ID" SortExpression="Resv_id" ReadOnly="True" />
                    <asp:BoundField DataField="Resv_restid" HeaderText="Restaurant id" SortExpression="Resv_restid" ReadOnly="True" />
                    <asp:BoundField DataField="Resv_date" HeaderText="Reservation date" SortExpression="Resv_date" />
                    <asp:BoundField DataField="Rest_time" HeaderText="Reservation time" SortExpression="Rest_time" />
                    <asp:BoundField DataField="Party_num" HeaderText="Number of ppl" SortExpression="Party_num" />
                    <asp:BoundField DataField="Resv_cusid" HeaderText="Customer Id" SortExpression="Resv_cusid" ReadOnly="True" />
                </Columns>
            </asp:GridView>
            <asp:SqlDataSource ID="reservationDataSource" runat="server" ConnectionString="<%$ ConnectionStrings:WebAppConnString %>"
                ProviderName="<%$ ConnectionStrings:WebAppConnString.ProviderName %>"
                DeleteCommand="DELETE FROM RESERVATION WHERE (Resv_id = @Resv_id) AND (Resv_restid =@Resv_restid)"
                UpdateCommand="UPDATE RESERVATION SET Resv_date =@Resv_date, Rest_time =@Rest_time, Party_num =@Party_num WHERE Resv_id =@Resv_id AND Resv_restid = @Resv_restid"
                SelectCommand="SELECT Resv_id,Resv_restid,cast(Resv_date as char) as Resv_date,Rest_time,Party_num,Resv_cusid from RESERVATION where Resv_restid=@RestaurantIdForRes 
            AND Resv_cusid=@customerId">
                <SelectParameters>
                    <asp:ControlParameter ControlID="customerNameDropDown" Name="customerId" PropertyName="SelectedValue" />
                    <asp:ControlParameter ControlID="restaurantIDDropDown" Name="RestaurantIdForRes" PropertyName="SelectedValue" />
                </SelectParameters>
            </asp:SqlDataSource>
            <br />
            <asp:DetailsView ID="ReservationDetailView" runat="server" DataSourceID="DetailResDataSource" Visible="false">
                <Fields>
                    <asp:CommandField ShowInsertButton="true" />
                </Fields>
            </asp:DetailsView>
            <asp:SqlDataSource ID="DetailResDataSource" runat="server" ConnectionString="<%$ ConnectionStrings:WebAppConnString %>"
                ProviderName="<%$ ConnectionStrings:WebAppConnString.ProviderName %>"
                SelectCommand="SELECT * from RESERVATION"
                InsertCommand="INSERT INTO RESERVATION VALUES(@Resv_id,@Resv_restid,@Resv_date,@Rest_time,@Party_num,@Resv_cusid)"></asp:SqlDataSource>

            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />



        </div>
    </form>
</body>
</html>
